name: tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'docs/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install requirements
      run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev libseccomp-dev

    - name: Run unit tests
      run: cargo test --verbose
